apiVersion: "v1"
kind: Pod
metadata:
  name: redis
  labels:
    name: redis
    app: tetrak8sdemo
spec:
  containers:
    - name: redis
      image: redis:latest
      ports:
        - containerPort: 6379         
          protocol: TCP
