apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis
    app:  tetrak8sdemo
spec:
  ports:
  - port: 6379
    name: redis
    targetPort: 6379
  selector:
    name: redis
    app: tetrak8sdemo
