apiVersion: "v1"
kind: Pod
metadata:
  name: web
  labels:
    name: web
    app: tetrak8sdemo
spec:
  containers:
    - name: web
      image: researcher6/web
      ports:
        - containerPort: 5000
          name: http
          protocol: TCP
